/* Generated by Yosys 0.10+12 (git sha1 UNKNOWN, gcc 10.1.0 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:1.1-684.10" *)
module Depth_10_20_Nodes_200_400_S002(N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, N331, N332, N333, N334, N335, N336, N337, N338, N339, N340, N341, N342, N343, N344);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:3.7-3.9" *)
  wire _170_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:12.7-12.10" *)
  wire _171_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:4.7-4.9" *)
  wire _172_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:5.7-5.9" *)
  wire _173_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:14.8-14.12" *)
  wire _174_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:15.8-15.12" *)
  wire _175_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:16.8-16.12" *)
  wire _176_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:17.8-17.12" *)
  wire _177_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:18.8-18.12" *)
  wire _178_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:19.8-19.12" *)
  wire _179_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:20.8-20.12" *)
  wire _180_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:22.8-22.12" *)
  wire _181_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:23.8-23.12" *)
  wire _182_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:24.8-24.12" *)
  wire _183_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:25.8-25.12" *)
  wire _184_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:27.8-27.12" *)
  wire _185_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:6.7-6.9" *)
  wire _186_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:7.7-7.9" *)
  wire _187_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:8.7-8.9" *)
  wire _188_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:9.7-9.9" *)
  wire _189_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:10.7-10.9" *)
  wire _190_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:11.7-11.9" *)
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:12.7-12.10" *)
  input N10;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:120.6-120.10" *)
  wire N102;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:122.6-122.10" *)
  wire N104;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:124.6-124.10" *)
  wire N106;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:125.6-125.10" *)
  wire N107;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:126.6-126.10" *)
  wire N108;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:127.6-127.10" *)
  wire N109;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:129.6-129.10" *)
  wire N111;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:134.6-134.10" *)
  wire N116;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:136.6-136.10" *)
  wire N118;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:137.6-137.10" *)
  wire N119;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:141.6-141.10" *)
  wire N123;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:156.6-156.10" *)
  wire N138;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:160.6-160.10" *)
  wire N142;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:162.6-162.10" *)
  wire N144;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:165.6-165.10" *)
  wire N147;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:169.6-169.10" *)
  wire N151;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:172.6-172.10" *)
  wire N154;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:179.6-179.10" *)
  wire N161;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:180.6-180.10" *)
  wire N162;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:181.6-181.10" *)
  wire N163;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:184.6-184.10" *)
  wire N166;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:190.6-190.10" *)
  wire N172;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:192.6-192.10" *)
  wire N174;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:194.6-194.10" *)
  wire N176;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:195.6-195.10" *)
  wire N177;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:196.6-196.10" *)
  wire N178;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:198.6-198.10" *)
  wire N180;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:201.6-201.10" *)
  wire N183;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:203.6-203.10" *)
  wire N185;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:206.6-206.10" *)
  wire N188;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:209.6-209.10" *)
  wire N191;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:211.6-211.10" *)
  wire N193;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:215.6-215.10" *)
  wire N197;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:216.6-216.10" *)
  wire N198;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:220.6-220.10" *)
  wire N202;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:232.6-232.10" *)
  wire N214;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:233.6-233.10" *)
  wire N215;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:242.6-242.10" *)
  wire N224;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:41.6-41.9" *)
  wire N23;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:251.6-251.10" *)
  wire N233;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:255.6-255.10" *)
  wire N237;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:260.6-260.10" *)
  wire N242;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:263.6-263.10" *)
  wire N245;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:265.6-265.10" *)
  wire N247;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:266.6-266.10" *)
  wire N248;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:267.6-267.10" *)
  wire N249;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:44.6-44.9" *)
  wire N26;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:282.6-282.10" *)
  wire N264;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:285.6-285.10" *)
  wire N267;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:288.6-288.10" *)
  wire N270;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:296.6-296.10" *)
  wire N278;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:301.6-301.10" *)
  wire N283;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:47.6-47.9" *)
  wire N29;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:316.6-316.10" *)
  wire N298;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:48.6-48.9" *)
  wire N30;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:321.6-321.10" *)
  wire N303;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:322.6-322.10" *)
  wire N304;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:327.6-327.10" *)
  wire N309;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:49.6-49.9" *)
  wire N31;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:333.6-333.10" *)
  wire N315;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:336.6-336.10" *)
  wire N318;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:337.6-337.10" *)
  wire N319;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:51.6-51.9" *)
  wire N33;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:14.8-14.12" *)
  output N331;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:15.8-15.12" *)
  output N332;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:16.8-16.12" *)
  output N333;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:17.8-17.12" *)
  output N334;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:18.8-18.12" *)
  output N335;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:19.8-19.12" *)
  output N336;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:20.8-20.12" *)
  output N337;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:21.8-21.12" *)
  output N338;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:22.8-22.12" *)
  output N339;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:52.6-52.9" *)
  wire N34;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:23.8-23.12" *)
  output N340;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:24.8-24.12" *)
  output N341;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:25.8-25.12" *)
  output N342;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:26.8-26.12" *)
  output N343;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:27.8-27.12" *)
  output N344;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:56.6-56.9" *)
  wire N38;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:59.6-59.9" *)
  wire N41;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:66.6-66.9" *)
  wire N48;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:7.7-7.9" *)
  input N5;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:68.6-68.9" *)
  wire N50;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:8.7-8.9" *)
  input N6;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:83.6-83.9" *)
  wire N65;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:9.7-9.9" *)
  input N7;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:92.6-92.9" *)
  wire N74;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:96.6-96.9" *)
  wire N78;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:97.6-97.9" *)
  wire N79;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:10.7-10.9" *)
  input N8;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:107.6-107.9" *)
  wire N89;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:11.7-11.9" *)
  input N9;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:110.6-110.9" *)
  wire N92;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:111.6-111.9" *)
  wire N93;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:112.6-112.9" *)
  wire N94;
  (* src = "./verilog/Depth_10_20_Nodes_200_400_S002.v:116.6-116.9" *)
  wire N98;
  NOT _210_ (
    .A(_172_),
    .Y(_192_)
  );
  NOT _211_ (
    .A(_189_),
    .Y(_193_)
  );
  NOT _212_ (
    .A(_186_),
    .Y(_194_)
  );
  NOT _213_ (
    .A(_190_),
    .Y(_195_)
  );
  AND _214_ (
    .A(_187_),
    .B(_192_),
    .Y(_196_)
  );
  AND _215_ (
    .A(_193_),
    .B(_194_),
    .Y(_197_)
  );
  AND _216_ (
    .A(_195_),
    .B(_197_),
    .Y(_198_)
  );
  AND _217_ (
    .A(_196_),
    .B(_198_),
    .Y(_179_)
  );
  OR _218_ (
    .A(_189_),
    .B(_173_),
    .Y(_199_)
  );
  OR _219_ (
    .A(_195_),
    .B(_199_),
    .Y(_200_)
  );
  OR _220_ (
    .A(_191_),
    .B(_188_),
    .Y(_201_)
  );
  OR _221_ (
    .A(_187_),
    .B(_201_),
    .Y(_202_)
  );
  OR _222_ (
    .A(_194_),
    .B(_190_),
    .Y(_203_)
  );
  AND _223_ (
    .A(_202_),
    .B(_203_),
    .Y(_204_)
  );
  AND _224_ (
    .A(_172_),
    .B(_200_),
    .Y(_205_)
  );
  AND _225_ (
    .A(_204_),
    .B(_205_),
    .Y(_175_)
  );
  OR _226_ (
    .A(_192_),
    .B(_202_),
    .Y(_185_)
  );
  AND _227_ (
    .A(_172_),
    .B(_193_),
    .Y(_206_)
  );
  OR _228_ (
    .A(_192_),
    .B(_189_),
    .Y(_207_)
  );
  AND _229_ (
    .A(_186_),
    .B(_190_),
    .Y(_208_)
  );
  AND _230_ (
    .A(_206_),
    .B(_208_),
    .Y(_178_)
  );
  AND _231_ (
    .A(_186_),
    .B(_202_),
    .Y(_209_)
  );
  OR _232_ (
    .A(_207_),
    .B(_209_),
    .Y(_180_)
  );
  assign N118 = N7;
  assign N138 = N7;
  assign N142 = N2;
  assign N144 = N2;
  assign N147 = N2;
  assign N116 = N2;
  assign N151 = N4;
  assign N154 = N2;
  assign N119 = N2;
  assign N161 = 1'h1;
  assign N162 = N10;
  assign N163 = N7;
  assign N166 = N4;
  assign N172 = 1'h0;
  assign N174 = 1'h1;
  assign N176 = N4;
  assign N177 = N8;
  assign N178 = N3;
  assign N180 = N2;
  assign N123 = N10;
  assign N183 = N10;
  assign N185 = N2;
  assign N188 = N7;
  assign N111 = N2;
  assign N191 = 1'h0;
  assign N193 = N10;
  assign N197 = N5;
  assign N198 = 1'h0;
  assign N109 = N4;
  assign N108 = 1'h1;
  assign N107 = N8;
  assign N106 = N2;
  assign N202 = N4;
  assign N104 = N2;
  assign N102 = N2;
  assign N214 = 1'h0;
  assign N215 = 1'h1;
  assign N224 = 1'h0;
  assign N23 = N8;
  assign N233 = 1'h1;
  assign N237 = N4;
  assign N242 = 1'h0;
  assign N245 = N4;
  assign N247 = N4;
  assign N248 = N4;
  assign N249 = N2;
  assign N26 = N2;
  assign N264 = 1'h1;
  assign N267 = 1'h1;
  assign N270 = 1'h1;
  assign N278 = N4;
  assign N283 = N8;
  assign N29 = N2;
  assign N298 = 1'h0;
  assign N30 = N4;
  assign N303 = 1'h1;
  assign N304 = 1'h1;
  assign N309 = 1'h1;
  assign N31 = N8;
  assign N315 = 1'h0;
  assign N318 = N2;
  assign N319 = N2;
  assign N33 = N8;
  assign N338 = 1'h1;
  assign N34 = N4;
  assign N343 = 1'h0;
  assign N38 = N8;
  assign N41 = N4;
  assign N48 = N2;
  assign N50 = 1'h0;
  assign N65 = N8;
  assign N74 = 1'h1;
  assign N78 = N4;
  assign N79 = N2;
  assign N89 = N8;
  assign N92 = N2;
  assign N93 = N4;
  assign N94 = N8;
  assign N98 = N5;
  assign _177_ = 1'h1;
  assign _176_ = 1'h0;
  assign _183_ = 1'h0;
  assign _182_ = 1'h1;
  assign _181_ = 1'h0;
  assign _174_ = 1'h1;
  assign _184_ = 1'h0;
  assign _191_ = N9;
  assign _188_ = N6;
  assign _187_ = N5;
  assign _172_ = N2;
  assign _189_ = N7;
  assign _171_ = N10;
  assign _186_ = N4;
  assign N342 = _184_;
  assign _190_ = N8;
  assign N336 = _179_;
  assign _170_ = N1;
  assign N331 = _174_;
  assign _173_ = N3;
  assign N339 = _181_;
  assign N332 = _175_;
  assign N340 = _182_;
  assign N341 = _183_;
  assign N344 = _185_;
  assign N333 = _176_;
  assign N334 = _177_;
  assign N335 = _178_;
  assign N337 = _180_;
endmodule
