/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_09.v:1.1-75.10" *)
module test_09(N1, N2, N3, N4, N5, N6, N7, N32, N33, N34, N35, N36, N37, N38);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "./verilog/test_09.v:3.7-3.9" *)
  wire _14_;
  (* src = "./verilog/test_09.v:4.7-4.9" *)
  wire _15_;
  (* src = "./verilog/test_09.v:5.7-5.9" *)
  wire _16_;
  (* src = "./verilog/test_09.v:11.8-11.11" *)
  wire _17_;
  (* src = "./verilog/test_09.v:12.8-12.11" *)
  wire _18_;
  (* src = "./verilog/test_09.v:13.8-13.11" *)
  wire _19_;
  (* src = "./verilog/test_09.v:14.8-14.11" *)
  wire _20_;
  (* src = "./verilog/test_09.v:15.8-15.11" *)
  wire _21_;
  (* src = "./verilog/test_09.v:16.8-16.11" *)
  wire _22_;
  (* src = "./verilog/test_09.v:6.7-6.9" *)
  wire _23_;
  (* src = "./verilog/test_09.v:7.7-7.9" *)
  wire _24_;
  (* src = "./verilog/test_09.v:8.7-8.9" *)
  wire _25_;
  (* src = "./verilog/test_09.v:9.7-9.9" *)
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  (* src = "./verilog/test_09.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_09.v:27.6-27.9" *)
  wire N16;
  (* src = "./verilog/test_09.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_09.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_09.v:11.8-11.11" *)
  output N32;
  (* src = "./verilog/test_09.v:12.8-12.11" *)
  output N33;
  (* src = "./verilog/test_09.v:13.8-13.11" *)
  output N34;
  (* src = "./verilog/test_09.v:14.8-14.11" *)
  output N35;
  (* src = "./verilog/test_09.v:15.8-15.11" *)
  output N36;
  (* src = "./verilog/test_09.v:16.8-16.11" *)
  output N37;
  (* src = "./verilog/test_09.v:17.8-17.11" *)
  output N38;
  (* src = "./verilog/test_09.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/test_09.v:7.7-7.9" *)
  input N5;
  (* src = "./verilog/test_09.v:8.7-8.9" *)
  input N6;
  (* src = "./verilog/test_09.v:9.7-9.9" *)
  input N7;
  NOT _34_ (
    .A(_15_),
    .Y(_27_)
  );
  NOT _35_ (
    .A(_23_),
    .Y(_28_)
  );
  AND _36_ (
    .A(_28_),
    .B(_25_),
    .Y(_22_)
  );
  OR _37_ (
    .A(_27_),
    .B(_14_),
    .Y(_18_)
  );
  OR _38_ (
    .A(_27_),
    .B(_24_),
    .Y(_29_)
  );
  OR _39_ (
    .A(_14_),
    .B(_24_),
    .Y(_30_)
  );
  AND _40_ (
    .A(_23_),
    .B(_30_),
    .Y(_31_)
  );
  AND _41_ (
    .A(_29_),
    .B(_31_),
    .Y(_32_)
  );
  NOT _42_ (
    .A(_32_),
    .Y(_21_)
  );
  OR _43_ (
    .A(_28_),
    .B(_29_),
    .Y(_19_)
  );
  AND _44_ (
    .A(_18_),
    .B(_29_),
    .Y(_33_)
  );
  OR _45_ (
    .A(_28_),
    .B(_33_),
    .Y(_20_)
  );
  assign N16 = N37;
  assign N38 = N33;
  assign _17_ = 1'h0;
  assign _15_ = N2;
  assign _23_ = N4;
  assign _16_ = N3;
  assign _14_ = N1;
  assign _24_ = N5;
  assign _26_ = N7;
  assign _25_ = N6;
  assign N37 = _22_;
  assign N32 = _17_;
  assign N33 = _18_;
  assign N36 = _21_;
  assign N35 = _20_;
  assign N34 = _19_;
endmodule
