/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_00.v:1.1-82.10" *)
module test_00(N1, N2, N3, N4, N34, N35, N36, N37, N38, N39, N40);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "./verilog/test_00.v:3.7-3.9" *)
  wire _26_;
  (* src = "./verilog/test_00.v:4.7-4.9" *)
  wire _27_;
  (* src = "./verilog/test_00.v:5.7-5.9" *)
  wire _28_;
  (* src = "./verilog/test_00.v:8.8-8.11" *)
  wire _29_;
  (* src = "./verilog/test_00.v:9.8-9.11" *)
  wire _30_;
  (* src = "./verilog/test_00.v:10.8-10.11" *)
  wire _31_;
  (* src = "./verilog/test_00.v:11.8-11.11" *)
  wire _32_;
  (* src = "./verilog/test_00.v:12.8-12.11" *)
  wire _33_;
  (* src = "./verilog/test_00.v:6.7-6.9" *)
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  (* src = "./verilog/test_00.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_00.v:23.6-23.9" *)
  wire N12;
  (* src = "./verilog/test_00.v:24.6-24.9" *)
  wire N13;
  (* src = "./verilog/test_00.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_00.v:37.6-37.9" *)
  wire N26;
  (* src = "./verilog/test_00.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_00.v:41.6-41.9" *)
  wire N30;
  (* src = "./verilog/test_00.v:44.6-44.9" *)
  wire N33;
  (* src = "./verilog/test_00.v:8.8-8.11" *)
  output N34;
  (* src = "./verilog/test_00.v:9.8-9.11" *)
  output N35;
  (* src = "./verilog/test_00.v:10.8-10.11" *)
  output N36;
  (* src = "./verilog/test_00.v:11.8-11.11" *)
  output N37;
  (* src = "./verilog/test_00.v:12.8-12.11" *)
  output N38;
  (* src = "./verilog/test_00.v:13.8-13.11" *)
  output N39;
  (* src = "./verilog/test_00.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/test_00.v:14.8-14.11" *)
  output N40;
  NOT _41_ (
    .A(_28_),
    .Y(_35_)
  );
  NOT _42_ (
    .A(_26_),
    .Y(_36_)
  );
  NOT _43_ (
    .A(_27_),
    .Y(_37_)
  );
  NOT _44_ (
    .A(_34_),
    .Y(_38_)
  );
  AND _45_ (
    .A(_35_),
    .B(_27_),
    .Y(_39_)
  );
  OR _46_ (
    .A(_28_),
    .B(_37_),
    .Y(_40_)
  );
  AND _47_ (
    .A(_38_),
    .B(_39_),
    .Y(_29_)
  );
  OR _48_ (
    .A(_36_),
    .B(_40_),
    .Y(_30_)
  );
  OR _49_ (
    .A(_38_),
    .B(_30_),
    .Y(_31_)
  );
  assign N12 = N3;
  assign N13 = N3;
  assign N26 = N1;
  assign N30 = N3;
  assign N33 = 1'h0;
  assign N39 = 1'h0;
  assign N40 = N4;
  assign _32_ = 1'h0;
  assign _33_ = 1'h0;
  assign _28_ = N3;
  assign _26_ = N1;
  assign _27_ = N2;
  assign N38 = _33_;
  assign _34_ = N4;
  assign N34 = _29_;
  assign N36 = _31_;
  assign N35 = _30_;
  assign N37 = _32_;
endmodule
