/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_04.v:1.1-73.10" *)
module test_04(N1, N2, N3, N4, N5, N6, N7, N36, N37);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "./verilog/test_04.v:3.7-3.9" *)
  wire _22_;
  (* src = "./verilog/test_04.v:4.7-4.9" *)
  wire _23_;
  (* src = "./verilog/test_04.v:5.7-5.9" *)
  wire _24_;
  (* src = "./verilog/test_04.v:11.8-11.11" *)
  wire _25_;
  (* src = "./verilog/test_04.v:12.8-12.11" *)
  wire _26_;
  (* src = "./verilog/test_04.v:6.7-6.9" *)
  wire _27_;
  (* src = "./verilog/test_04.v:7.7-7.9" *)
  wire _28_;
  (* src = "./verilog/test_04.v:8.7-8.9" *)
  wire _29_;
  (* src = "./verilog/test_04.v:9.7-9.9" *)
  wire _30_;
  (* src = "./verilog/test_04.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_04.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_04.v:26.6-26.9" *)
  wire N20;
  (* src = "./verilog/test_04.v:27.6-27.9" *)
  wire N21;
  (* src = "./verilog/test_04.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_04.v:40.6-40.9" *)
  wire N34;
  (* src = "./verilog/test_04.v:11.8-11.11" *)
  output N36;
  (* src = "./verilog/test_04.v:12.8-12.11" *)
  output N37;
  (* src = "./verilog/test_04.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/test_04.v:7.7-7.9" *)
  input N5;
  (* src = "./verilog/test_04.v:8.7-8.9" *)
  input N6;
  (* src = "./verilog/test_04.v:9.7-9.9" *)
  input N7;
  assign N20 = N4;
  assign N21 = N3;
  assign N34 = 1'h0;
  assign _25_ = 1'h1;
  assign _26_ = 1'h0;
  assign _24_ = N3;
  assign _30_ = N7;
  assign _29_ = N6;
  assign _23_ = N2;
  assign _28_ = N5;
  assign _27_ = N4;
  assign N37 = _26_;
  assign _22_ = N1;
  assign N36 = _25_;
endmodule
