/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_02.v:1.1-85.10" *)
module test_02(N1, N2, N3, N4, N5, N32, N33, N34, N35, N36, N37, N38, N39, N40, N41, N42);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  (* src = "./verilog/test_02.v:3.7-3.9" *)
  wire _49_;
  (* src = "./verilog/test_02.v:4.7-4.9" *)
  wire _50_;
  (* src = "./verilog/test_02.v:5.7-5.9" *)
  wire _51_;
  (* src = "./verilog/test_02.v:9.8-9.11" *)
  wire _52_;
  (* src = "./verilog/test_02.v:10.8-10.11" *)
  wire _53_;
  (* src = "./verilog/test_02.v:11.8-11.11" *)
  wire _54_;
  (* src = "./verilog/test_02.v:12.8-12.11" *)
  wire _55_;
  (* src = "./verilog/test_02.v:13.8-13.11" *)
  wire _56_;
  (* src = "./verilog/test_02.v:15.8-15.11" *)
  wire _57_;
  (* src = "./verilog/test_02.v:16.8-16.11" *)
  wire _58_;
  (* src = "./verilog/test_02.v:6.7-6.9" *)
  wire _59_;
  (* src = "./verilog/test_02.v:17.8-17.11" *)
  wire _60_;
  (* src = "./verilog/test_02.v:19.8-19.11" *)
  wire _61_;
  (* src = "./verilog/test_02.v:7.7-7.9" *)
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  (* src = "./verilog/test_02.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_02.v:25.6-25.9" *)
  wire N10;
  (* src = "./verilog/test_02.v:28.6-28.9" *)
  wire N13;
  (* src = "./verilog/test_02.v:29.6-29.9" *)
  wire N14;
  (* src = "./verilog/test_02.v:33.6-33.9" *)
  wire N18;
  (* src = "./verilog/test_02.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_02.v:37.6-37.9" *)
  wire N22;
  (* src = "./verilog/test_02.v:39.6-39.9" *)
  wire N24;
  (* src = "./verilog/test_02.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_02.v:9.8-9.11" *)
  output N32;
  (* src = "./verilog/test_02.v:10.8-10.11" *)
  output N33;
  (* src = "./verilog/test_02.v:11.8-11.11" *)
  output N34;
  (* src = "./verilog/test_02.v:12.8-12.11" *)
  output N35;
  (* src = "./verilog/test_02.v:13.8-13.11" *)
  output N36;
  (* src = "./verilog/test_02.v:14.8-14.11" *)
  output N37;
  (* src = "./verilog/test_02.v:15.8-15.11" *)
  output N38;
  (* src = "./verilog/test_02.v:16.8-16.11" *)
  output N39;
  (* src = "./verilog/test_02.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/test_02.v:17.8-17.11" *)
  output N40;
  (* src = "./verilog/test_02.v:18.8-18.11" *)
  output N41;
  (* src = "./verilog/test_02.v:19.8-19.11" *)
  output N42;
  (* src = "./verilog/test_02.v:7.7-7.9" *)
  input N5;
  (* src = "./verilog/test_02.v:21.6-21.8" *)
  wire N6;
  (* src = "./verilog/test_02.v:22.6-22.8" *)
  wire N7;
  (* src = "./verilog/test_02.v:23.6-23.8" *)
  wire N8;
  NOT _69_ (
    .A(_49_),
    .Y(_58_)
  );
  NOT _70_ (
    .A(_62_),
    .Y(_63_)
  );
  NOT _71_ (
    .A(_50_),
    .Y(_60_)
  );
  NOT _72_ (
    .A(_51_),
    .Y(_64_)
  );
  AND _73_ (
    .A(_49_),
    .B(_63_),
    .Y(_56_)
  );
  AND _74_ (
    .A(_58_),
    .B(_64_),
    .Y(_65_)
  );
  AND _75_ (
    .A(_59_),
    .B(_65_),
    .Y(_66_)
  );
  OR _76_ (
    .A(_62_),
    .B(_60_),
    .Y(_67_)
  );
  OR _77_ (
    .A(_66_),
    .B(_67_),
    .Y(_57_)
  );
  AND _78_ (
    .A(_49_),
    .B(_60_),
    .Y(_68_)
  );
  AND _79_ (
    .A(_64_),
    .B(_68_),
    .Y(_53_)
  );
  assign N10 = N39;
  assign N13 = N40;
  assign N14 = N40;
  assign N18 = N40;
  assign N22 = N1;
  assign N24 = N39;
  assign N37 = N2;
  assign N41 = N1;
  assign N6 = N39;
  assign N7 = N40;
  assign N8 = N40;
  assign _52_ = 1'h0;
  assign _54_ = 1'h0;
  assign _55_ = 1'h0;
  assign _61_ = 1'h0;
  assign _49_ = N1;
  assign _62_ = N5;
  assign N36 = _56_;
  assign _50_ = N2;
  assign N40 = _60_;
  assign N39 = _58_;
  assign _51_ = N3;
  assign _59_ = N4;
  assign N38 = _57_;
  assign N42 = _61_;
  assign N35 = _55_;
  assign N34 = _54_;
  assign N33 = _53_;
  assign N32 = _52_;
endmodule
