/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_06.v:1.1-62.10" *)
module test_06(N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, N19, N20, N21, N22, N23, N24, N25, N26, N27, N28, N29, N30, N31, N32, N33);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  (* src = "./verilog/test_06.v:3.7-3.9" *)
  wire _52_;
  (* src = "./verilog/test_06.v:12.7-12.10" *)
  wire _53_;
  (* src = "./verilog/test_06.v:14.8-14.11" *)
  wire _54_;
  (* src = "./verilog/test_06.v:4.7-4.9" *)
  wire _55_;
  (* src = "./verilog/test_06.v:15.8-15.11" *)
  wire _56_;
  (* src = "./verilog/test_06.v:17.8-17.11" *)
  wire _57_;
  (* src = "./verilog/test_06.v:18.8-18.11" *)
  wire _58_;
  (* src = "./verilog/test_06.v:19.8-19.11" *)
  wire _59_;
  (* src = "./verilog/test_06.v:21.8-21.11" *)
  wire _60_;
  (* src = "./verilog/test_06.v:22.8-22.11" *)
  wire _61_;
  (* src = "./verilog/test_06.v:23.8-23.11" *)
  wire _62_;
  (* src = "./verilog/test_06.v:24.8-24.11" *)
  wire _63_;
  (* src = "./verilog/test_06.v:5.7-5.9" *)
  wire _64_;
  (* src = "./verilog/test_06.v:25.8-25.11" *)
  wire _65_;
  (* src = "./verilog/test_06.v:26.8-26.11" *)
  wire _66_;
  (* src = "./verilog/test_06.v:27.8-27.11" *)
  wire _67_;
  (* src = "./verilog/test_06.v:28.8-28.11" *)
  wire _68_;
  (* src = "./verilog/test_06.v:6.7-6.9" *)
  wire _69_;
  (* src = "./verilog/test_06.v:7.7-7.9" *)
  wire _70_;
  (* src = "./verilog/test_06.v:8.7-8.9" *)
  wire _71_;
  (* src = "./verilog/test_06.v:9.7-9.9" *)
  wire _72_;
  (* src = "./verilog/test_06.v:10.7-10.9" *)
  wire _73_;
  (* src = "./verilog/test_06.v:11.7-11.9" *)
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _80_;
  wire _81_;
  (* src = "./verilog/test_06.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_06.v:12.7-12.10" *)
  input N10;
  (* src = "./verilog/test_06.v:37.6-37.9" *)
  wire N18;
  (* src = "./verilog/test_06.v:14.8-14.11" *)
  output N19;
  (* src = "./verilog/test_06.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_06.v:15.8-15.11" *)
  output N20;
  (* src = "./verilog/test_06.v:16.8-16.11" *)
  output N21;
  (* src = "./verilog/test_06.v:17.8-17.11" *)
  output N22;
  (* src = "./verilog/test_06.v:18.8-18.11" *)
  output N23;
  (* src = "./verilog/test_06.v:19.8-19.11" *)
  output N24;
  (* src = "./verilog/test_06.v:20.8-20.11" *)
  output N25;
  (* src = "./verilog/test_06.v:21.8-21.11" *)
  output N26;
  (* src = "./verilog/test_06.v:22.8-22.11" *)
  output N27;
  (* src = "./verilog/test_06.v:23.8-23.11" *)
  output N28;
  (* src = "./verilog/test_06.v:24.8-24.11" *)
  output N29;
  (* src = "./verilog/test_06.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_06.v:25.8-25.11" *)
  output N30;
  (* src = "./verilog/test_06.v:26.8-26.11" *)
  output N31;
  (* src = "./verilog/test_06.v:27.8-27.11" *)
  output N32;
  (* src = "./verilog/test_06.v:28.8-28.11" *)
  output N33;
  (* src = "./verilog/test_06.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/test_06.v:7.7-7.9" *)
  input N5;
  (* src = "./verilog/test_06.v:8.7-8.9" *)
  input N6;
  (* src = "./verilog/test_06.v:9.7-9.9" *)
  input N7;
  (* src = "./verilog/test_06.v:10.7-10.9" *)
  input N8;
  (* src = "./verilog/test_06.v:11.7-11.9" *)
  input N9;
  NOT _82_ (
    .A(_72_),
    .Y(_68_)
  );
  NOT _83_ (
    .A(_52_),
    .Y(_58_)
  );
  AND _84_ (
    .A(_70_),
    .B(_74_),
    .Y(_75_)
  );
  NOT _85_ (
    .A(_75_),
    .Y(_62_)
  );
  AND _86_ (
    .A(_70_),
    .B(_69_),
    .Y(_76_)
  );
  NOT _87_ (
    .A(_76_),
    .Y(_59_)
  );
  AND _88_ (
    .A(_71_),
    .B(_55_),
    .Y(_77_)
  );
  NOT _89_ (
    .A(_77_),
    .Y(_65_)
  );
  OR _90_ (
    .A(_53_),
    .B(_64_),
    .Y(_78_)
  );
  NOT _91_ (
    .A(_78_),
    .Y(_57_)
  );
  AND _92_ (
    .A(_69_),
    .B(_73_),
    .Y(_79_)
  );
  AND _93_ (
    .A(_53_),
    .B(_79_),
    .Y(_80_)
  );
  OR _94_ (
    .A(_55_),
    .B(_64_),
    .Y(_81_)
  );
  OR _95_ (
    .A(_80_),
    .B(_81_),
    .Y(_63_)
  );
  assign N18 = N23;
  assign N21 = N1;
  assign N25 = N8;
  assign _61_ = 1'h0;
  assign _60_ = 1'h0;
  assign _67_ = 1'h0;
  assign _56_ = 1'h0;
  assign _54_ = 1'h1;
  assign _66_ = 1'h1;
  assign _70_ = N5;
  assign _74_ = N9;
  assign N28 = _62_;
  assign _72_ = N7;
  assign N33 = _68_;
  assign _69_ = N4;
  assign N24 = _59_;
  assign _71_ = N6;
  assign _55_ = N2;
  assign N30 = _65_;
  assign _52_ = N1;
  assign N23 = _58_;
  assign _73_ = N8;
  assign _53_ = N10;
  assign _64_ = N3;
  assign N31 = _66_;
  assign N19 = _54_;
  assign N20 = _56_;
  assign N32 = _67_;
  assign N26 = _60_;
  assign N22 = _57_;
  assign N27 = _61_;
  assign N29 = _63_;
endmodule
