/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_03.v:1.1-77.10" *)
module test_03(N1, N2, N3, N4, N5, N32, N33, N34, N35, N36, N37, N38);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "./verilog/test_03.v:3.7-3.9" *)
  wire _11_;
  (* src = "./verilog/test_03.v:4.7-4.9" *)
  wire _12_;
  (* src = "./verilog/test_03.v:5.7-5.9" *)
  wire _13_;
  (* src = "./verilog/test_03.v:9.8-9.11" *)
  wire _14_;
  (* src = "./verilog/test_03.v:10.8-10.11" *)
  wire _15_;
  (* src = "./verilog/test_03.v:12.8-12.11" *)
  wire _16_;
  (* src = "./verilog/test_03.v:13.8-13.11" *)
  wire _17_;
  (* src = "./verilog/test_03.v:14.8-14.11" *)
  wire _18_;
  (* src = "./verilog/test_03.v:15.8-15.11" *)
  wire _19_;
  (* src = "./verilog/test_03.v:6.7-6.9" *)
  wire _20_;
  (* src = "./verilog/test_03.v:7.7-7.9" *)
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "./verilog/test_03.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_03.v:23.6-23.9" *)
  wire N12;
  (* src = "./verilog/test_03.v:25.6-25.9" *)
  wire N14;
  (* src = "./verilog/test_03.v:26.6-26.9" *)
  wire N15;
  (* src = "./verilog/test_03.v:29.6-29.9" *)
  wire N18;
  (* src = "./verilog/test_03.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_03.v:31.6-31.9" *)
  wire N20;
  (* src = "./verilog/test_03.v:33.6-33.9" *)
  wire N22;
  (* src = "./verilog/test_03.v:37.6-37.9" *)
  wire N26;
  (* src = "./verilog/test_03.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_03.v:9.8-9.11" *)
  output N32;
  (* src = "./verilog/test_03.v:10.8-10.11" *)
  output N33;
  (* src = "./verilog/test_03.v:11.8-11.11" *)
  output N34;
  (* src = "./verilog/test_03.v:12.8-12.11" *)
  output N35;
  (* src = "./verilog/test_03.v:13.8-13.11" *)
  output N36;
  (* src = "./verilog/test_03.v:14.8-14.11" *)
  output N37;
  (* src = "./verilog/test_03.v:15.8-15.11" *)
  output N38;
  (* src = "./verilog/test_03.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/test_03.v:7.7-7.9" *)
  input N5;
  NOT _31_ (
    .A(_13_),
    .Y(_22_)
  );
  NOT _32_ (
    .A(_21_),
    .Y(_23_)
  );
  NOT _33_ (
    .A(_20_),
    .Y(_24_)
  );
  OR _34_ (
    .A(_11_),
    .B(_22_),
    .Y(_19_)
  );
  AND _35_ (
    .A(_22_),
    .B(_12_),
    .Y(_25_)
  );
  OR _36_ (
    .A(_11_),
    .B(_25_),
    .Y(_26_)
  );
  NOT _37_ (
    .A(_26_),
    .Y(_18_)
  );
  OR _38_ (
    .A(_23_),
    .B(_20_),
    .Y(_27_)
  );
  OR _39_ (
    .A(_19_),
    .B(_27_),
    .Y(_28_)
  );
  OR _40_ (
    .A(_12_),
    .B(_28_),
    .Y(_15_)
  );
  AND _41_ (
    .A(_13_),
    .B(_12_),
    .Y(_29_)
  );
  NOT _42_ (
    .A(_29_),
    .Y(_16_)
  );
  AND _43_ (
    .A(_11_),
    .B(_13_),
    .Y(_30_)
  );
  OR _44_ (
    .A(_24_),
    .B(_30_),
    .Y(_17_)
  );
  assign N15 = N1;
  assign N18 = N3;
  assign N20 = N3;
  assign N22 = N1;
  assign N26 = N4;
  assign N34 = 1'h1;
  assign N14 = 1'h1;
  assign N12 = N3;
  assign _14_ = 1'h1;
  assign _11_ = N1;
  assign _13_ = N3;
  assign N38 = _19_;
  assign _12_ = N2;
  assign _21_ = N5;
  assign _20_ = N4;
  assign N32 = _14_;
  assign N37 = _18_;
  assign N33 = _15_;
  assign N35 = _16_;
  assign N36 = _17_;
endmodule
