/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_07.v:1.1-81.10" *)
module test_07(N1, N2, N3, N26, N27, N28, N29, N30, N31, N32, N33, N34, N35, N36, N37, N38, N39);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "./verilog/test_07.v:3.7-3.9" *)
  wire _33_;
  (* src = "./verilog/test_07.v:4.7-4.9" *)
  wire _34_;
  (* src = "./verilog/test_07.v:7.8-7.11" *)
  wire _35_;
  (* src = "./verilog/test_07.v:8.8-8.11" *)
  wire _36_;
  (* src = "./verilog/test_07.v:9.8-9.11" *)
  wire _37_;
  (* src = "./verilog/test_07.v:10.8-10.11" *)
  wire _38_;
  (* src = "./verilog/test_07.v:5.7-5.9" *)
  wire _39_;
  (* src = "./verilog/test_07.v:11.8-11.11" *)
  wire _40_;
  (* src = "./verilog/test_07.v:12.8-12.11" *)
  wire _41_;
  (* src = "./verilog/test_07.v:13.8-13.11" *)
  wire _42_;
  (* src = "./verilog/test_07.v:14.8-14.11" *)
  wire _43_;
  (* src = "./verilog/test_07.v:15.8-15.11" *)
  wire _44_;
  (* src = "./verilog/test_07.v:17.8-17.11" *)
  wire _45_;
  (* src = "./verilog/test_07.v:18.8-18.11" *)
  wire _46_;
  (* src = "./verilog/test_07.v:19.8-19.11" *)
  wire _47_;
  (* src = "./verilog/test_07.v:20.8-20.11" *)
  wire _48_;
  wire _49_;
  (* src = "./verilog/test_07.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_07.v:28.6-28.9" *)
  wire N10;
  (* src = "./verilog/test_07.v:33.6-33.9" *)
  wire N15;
  (* src = "./verilog/test_07.v:35.6-35.9" *)
  wire N17;
  (* src = "./verilog/test_07.v:37.6-37.9" *)
  wire N19;
  (* src = "./verilog/test_07.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_07.v:7.8-7.11" *)
  output N26;
  (* src = "./verilog/test_07.v:8.8-8.11" *)
  output N27;
  (* src = "./verilog/test_07.v:9.8-9.11" *)
  output N28;
  (* src = "./verilog/test_07.v:10.8-10.11" *)
  output N29;
  (* src = "./verilog/test_07.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_07.v:11.8-11.11" *)
  output N30;
  (* src = "./verilog/test_07.v:12.8-12.11" *)
  output N31;
  (* src = "./verilog/test_07.v:13.8-13.11" *)
  output N32;
  (* src = "./verilog/test_07.v:14.8-14.11" *)
  output N33;
  (* src = "./verilog/test_07.v:15.8-15.11" *)
  output N34;
  (* src = "./verilog/test_07.v:16.8-16.11" *)
  output N35;
  (* src = "./verilog/test_07.v:17.8-17.11" *)
  output N36;
  (* src = "./verilog/test_07.v:18.8-18.11" *)
  output N37;
  (* src = "./verilog/test_07.v:19.8-19.11" *)
  output N38;
  (* src = "./verilog/test_07.v:20.8-20.11" *)
  output N39;
  (* src = "./verilog/test_07.v:23.6-23.8" *)
  wire N5;
  (* src = "./verilog/test_07.v:24.6-24.8" *)
  wire N6;
  NOT _50_ (
    .A(_39_),
    .Y(_41_)
  );
  NOT _51_ (
    .A(_33_),
    .Y(_49_)
  );
  NOT _52_ (
    .A(_34_),
    .Y(_37_)
  );
  AND _53_ (
    .A(_33_),
    .B(_34_),
    .Y(_40_)
  );
  OR _54_ (
    .A(_49_),
    .B(_34_),
    .Y(_35_)
  );
  AND _55_ (
    .A(_41_),
    .B(_33_),
    .Y(_42_)
  );
  AND _56_ (
    .A(_39_),
    .B(_34_),
    .Y(_45_)
  );
  BUF _57_ (
    .A(_34_),
    .Y(_48_)
  );
  assign N10 = N3;
  assign N15 = N31;
  assign N17 = N1;
  assign N19 = N28;
  assign N35 = N3;
  assign N5 = N31;
  assign N6 = N30;
  assign _47_ = 1'h1;
  assign _46_ = 1'h1;
  assign _44_ = 1'h0;
  assign _43_ = 1'h1;
  assign _38_ = 1'h0;
  assign _36_ = 1'h0;
  assign _39_ = N3;
  assign N31 = _41_;
  assign _33_ = N1;
  assign _34_ = N2;
  assign N30 = _40_;
  assign N26 = _35_;
  assign N28 = _37_;
  assign N32 = _42_;
  assign N36 = _45_;
  assign N39 = _48_;
  assign N27 = _36_;
  assign N29 = _38_;
  assign N33 = _43_;
  assign N34 = _44_;
  assign N37 = _46_;
  assign N38 = _47_;
endmodule
