/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_08.v:1.1-49.10" *)
module test_08(N1, N2, N3, N4, N5, N23, N24);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "./verilog/test_08.v:3.7-3.9" *)
  wire _16_;
  (* src = "./verilog/test_08.v:4.7-4.9" *)
  wire _17_;
  (* src = "./verilog/test_08.v:9.8-9.11" *)
  wire _18_;
  (* src = "./verilog/test_08.v:10.8-10.11" *)
  wire _19_;
  (* src = "./verilog/test_08.v:5.7-5.9" *)
  wire _20_;
  (* src = "./verilog/test_08.v:6.7-6.9" *)
  wire _21_;
  (* src = "./verilog/test_08.v:7.7-7.9" *)
  wire _22_;
  (* src = "./verilog/test_08.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_08.v:18.6-18.9" *)
  wire N12;
  (* src = "./verilog/test_08.v:19.6-19.9" *)
  wire N13;
  (* src = "./verilog/test_08.v:24.6-24.9" *)
  wire N18;
  (* src = "./verilog/test_08.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_08.v:9.8-9.11" *)
  output N23;
  (* src = "./verilog/test_08.v:10.8-10.11" *)
  output N24;
  (* src = "./verilog/test_08.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_08.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/test_08.v:7.7-7.9" *)
  input N5;
  assign N12 = N2;
  assign N13 = N3;
  assign N18 = N1;
  assign _18_ = 1'h0;
  assign _19_ = 1'h1;
  assign _17_ = N2;
  assign _20_ = N3;
  assign _22_ = N5;
  assign _21_ = N4;
  assign N24 = _19_;
  assign _16_ = N1;
  assign N23 = _18_;
endmodule
