/* Generated by Yosys 0.9+4272 (git sha1 10f8b75d, gcc 5.5.0-12ubuntu1~16.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/test_05.v:1.1-61.10" *)
module test_05(N1, N2, N3, N4, N5, N6, N7, N8, N9, N31, N32);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "./verilog/test_05.v:3.7-3.9" *)
  wire _24_;
  (* src = "./verilog/test_05.v:4.7-4.9" *)
  wire _25_;
  (* src = "./verilog/test_05.v:5.7-5.9" *)
  wire _26_;
  (* src = "./verilog/test_05.v:13.8-13.11" *)
  wire _27_;
  (* src = "./verilog/test_05.v:14.8-14.11" *)
  wire _28_;
  (* src = "./verilog/test_05.v:6.7-6.9" *)
  wire _29_;
  (* src = "./verilog/test_05.v:7.7-7.9" *)
  wire _30_;
  (* src = "./verilog/test_05.v:8.7-8.9" *)
  wire _31_;
  (* src = "./verilog/test_05.v:9.7-9.9" *)
  wire _32_;
  (* src = "./verilog/test_05.v:10.7-10.9" *)
  wire _33_;
  (* src = "./verilog/test_05.v:11.7-11.9" *)
  wire _34_;
  (* src = "./verilog/test_05.v:3.7-3.9" *)
  input N1;
  (* src = "./verilog/test_05.v:20.6-20.9" *)
  wire N14;
  (* src = "./verilog/test_05.v:21.6-21.9" *)
  wire N15;
  (* src = "./verilog/test_05.v:23.6-23.9" *)
  wire N17;
  (* src = "./verilog/test_05.v:4.7-4.9" *)
  input N2;
  (* src = "./verilog/test_05.v:31.6-31.9" *)
  wire N25;
  (* src = "./verilog/test_05.v:5.7-5.9" *)
  input N3;
  (* src = "./verilog/test_05.v:13.8-13.11" *)
  output N31;
  (* src = "./verilog/test_05.v:14.8-14.11" *)
  output N32;
  (* src = "./verilog/test_05.v:6.7-6.9" *)
  input N4;
  (* src = "./verilog/test_05.v:7.7-7.9" *)
  input N5;
  (* src = "./verilog/test_05.v:8.7-8.9" *)
  input N6;
  (* src = "./verilog/test_05.v:9.7-9.9" *)
  input N7;
  (* src = "./verilog/test_05.v:10.7-10.9" *)
  input N8;
  (* src = "./verilog/test_05.v:11.7-11.9" *)
  input N9;
  assign N14 = N9;
  assign N15 = N6;
  assign N17 = N6;
  assign N25 = N9;
  assign _28_ = 1'h1;
  assign _27_ = 1'h0;
  assign _31_ = N6;
  assign _32_ = N7;
  assign _24_ = N1;
  assign _25_ = N2;
  assign _29_ = N4;
  assign _26_ = N3;
  assign _34_ = N9;
  assign _30_ = N5;
  assign N31 = _27_;
  assign _33_ = N8;
  assign N32 = _28_;
endmodule
